# Generated by Django 5.0.6 on 2024-07-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0004_bankaccount_bank_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=255)),
                ('scode', models.CharField(max_length=255)),
                ('orderno', models.CharField(default='', max_length=255, null=True)),
                ('orderid', models.CharField(max_length=255)),
                ('money', models.BigIntegerField()),
                ('bankname', models.CharField(max_length=255, null=True)),
                ('accountno', models.CharField(max_length=255)),
                ('accountname', models.CharField(max_length=255)),
                ('bankcode', models.CharField(max_length=255)),
                ('is_auto', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_report', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settle_payout_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settle_payout',
            },
        ),
    ]
