# Generated by Django 5.0.6 on 2024-08-02 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_bank_type'),
        ('settle_payout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlepayout',
            name='bankname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='settlepayout',
            name='did',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='settlepayout',
            name='process_bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='settlepayout',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settlepayout',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settle_payout_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
