# Generated by Django 5.0.6 on 2024-08-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_bank_type'),
        ('settle_payout', '0002_alter_settlepayout_bankname_alter_settlepayout_did_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlepayout',
            name='process_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank'),
        ),
    ]
