# Generated by Django 5.0.6 on 2024-08-02 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_payout', '0003_alter_settlepayout_process_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlepayout',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settle_payout_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
