# Generated by Django 5.0.6 on 2024-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_payout', '0004_alter_settlepayout_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlepayout',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
