# Generated by Django 5.0.6 on 2024-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_payout', '0006_alter_settlepayout_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlepayout',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
