# Generated by Django 5.0.6 on 2024-11-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_payout', '0007_alter_settlepayout_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlepayout',
            name='money',
            field=models.BigIntegerField(),
        ),
    ]
