# Generated by Django 5.0.6 on 2025-01-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_payout', '0008_alter_settlepayout_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlepayout',
            name='memo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
