# Generated by Django 5.0.6 on 2025-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_payout', '0009_settlepayout_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlepayout',
            name='manual_withdraw',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
