# Generated by Django 5.0.6 on 2024-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
