# Generated by Django 5.0.6 on 2024-06-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
