# Generated by Django 5.0.6 on 2024-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccount_password_bankaccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_type',
            field=models.CharField(default='IN', max_length=255),
        ),
    ]
