# Generated by Django 5.0.6 on 2024-08-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bankcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
