# Generated by Django 5.0.6 on 2024-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bank_bankcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='last_logged_in',
            field=models.DateTimeField(null=True),
        ),
    ]
