# Generated by Django 5.0.6 on 2024-12-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_bankaccount_last_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='corp_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
