# Generated by Django 5.0.6 on 2024-12-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_bankaccount_corp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='corp_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
