# Generated by Django 5.0.6 on 2024-07-12 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountinout',
            name='date_record',
            field=models.DateField(default=datetime.date(2024, 7, 12)),
        ),
    ]
