# Generated by Django 5.0.6 on 2024-07-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_amountinout_date_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountinout',
            name='date_record',
        ),
    ]
