# Generated by Django 5.0.6 on 2024-09-08 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User2Fa',
        ),
        migrations.AlterModelTable(
            name='user2fa',
            table='user_2fa',
        ),
    ]
