# Generated by Django 5.0.6 on 2024-09-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_rename_profile_user2fa_alter_user2fa_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2fa',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
