# Generated by Django 5.0.6 on 2024-09-08 14:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeedeposit_accountname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 25, 58, 179487))),
                ('start_balance', models.BigIntegerField(default=0)),
                ('end_time', models.DateTimeField(null=True)),
                ('end_balance', models.BigIntegerField(default=0)),
                ('status', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_working_session',
            },
        ),
    ]
