# Generated by Django 5.0.6 on 2024-09-03 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeworkingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 23, 52, 2, 530175)),
        ),
        migrations.AlterModelTable(
            name='employeeworkingsession',
            table='employee_working_session',
        ),
    ]
