# Generated by Django 5.0.6 on 2024-09-08 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 22, 33, 21, 140045)),
        ),
    ]
