# Generated by Django 5.0.6 on 2024-09-04 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkingsession',
            name='end_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='start_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 15, 41, 35, 974617)),
        ),
    ]
