# Generated by Django 5.0.6 on 2024-09-12 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employeeworkingsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 14, 21, 42, 148982), null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 14, 21, 42, 148949)),
        ),
    ]
