# Generated by Django 5.0.6 on 2024-09-16 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employeeworkingsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 16, 14, 57, 2731, tzinfo=datetime.timezone.utc)),
        ),
    ]
