# Generated by Django 5.0.6 on 2024-09-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default='2024-09-16 16:22:59'),
        ),
    ]
