# Generated by Django 5.0.6 on 2024-09-17 02:03

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='end_time',
            field=timezone_field.fields.TimeZoneField(default='Asia/Bangkok'),
        ),
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=timezone_field.fields.TimeZoneField(default='Asia/Bangkok'),
        ),
    ]
