# Generated by Django 5.0.6 on 2024-09-17 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
