# Generated by Django 5.0.6 on 2025-07-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkingsession',
            name='deposit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='total_amount_payout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='total_payout',
            field=models.IntegerField(default=0),
        ),
    ]
