# Generated by Django 5.0.6 on 2025-06-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employeeworkingsession_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeworkingsession',
            old_name='end_balance',
            new_name='balance1',
        ),
        migrations.RenameField(
            model_name='employeeworkingsession',
            old_name='start_balance',
            new_name='balance2',
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='balance3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='deposit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='total_payout',
            field=models.IntegerField(default=0),
        ),
    ]
