# Generated by Django 5.0.6 on 2025-07-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_employeeworkingsession_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkingsession',
            name='total_amount_settle',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkingsession',
            name='total_settle',
            field=models.IntegerField(default=0),
        ),
    ]
