# Generated by Django 5.0.6 on 2025-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_employeeworkingsession_total_amount_settle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkingsession',
            name='total_amount_payout',
            field=models.BigIntegerField(default=0),
        ),
    ]
