# Generated by Django 5.0.6 on 2025-02-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('incomingorderid', models.CharField(max_length=255, null=True, unique=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('orderid', models.CharField(max_length=255, null=True, unique=True)),
                ('scode', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_number', models.CharField(default='', max_length=255)),
                ('transfer_code', models.CharField(max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_history',
                'unique_together': {('account_number', 'transaction_number')},
            },
        ),
    ]
