# Generated by Django 5.0.6 on 2025-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='transaction_code',
            new_name='transfer_code',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='incomingorderid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='orderid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='scode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
