# Generated by Django 5.0.6 on 2025-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transactionhistory_transfer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
