# Generated by Django 5.0.6 on 2025-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_transaction_code_transactionhistory_transfer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
