# Generated by Django 5.0.6 on 2025-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactionhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transfer_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
