# Generated by Django 5.0.6 on 2025-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactionhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='payername',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
