# Generated by Django 5.0.6 on 2025-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transactionhistory_transfer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_number',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
