# Generated by Django 5.0.6 on 2025-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transactionhistory_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('account_number', 'transaction_number')},
        ),
    ]
