# Generated by Django 5.0.6 on 2024-06-23 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=255)),
                ('scode', models.CharField(max_length=255)),
                ('orderno', models.CharField(max_length=255)),
                ('orderid', models.CharField(max_length=255)),
                ('money', models.BigIntegerField()),
                ('bankname', models.CharField(max_length=255)),
                ('accountno', models.CharField(max_length=255)),
                ('accountname', models.CharField(max_length=255)),
                ('bankcode', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout',
            },
        ),
    ]
