# Generated by Django 5.0.6 on 2024-07-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_bank_type'),
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='process_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bankname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
