# Generated by Django 5.0.6 on 2024-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
