# Generated by Django 5.0.6 on 2024-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0002_payout_is_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='orderno',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
