# Generated by Django 5.0.6 on 2024-07-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_timeline_alter_payout_process_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='partner_bankcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
