# Generated by Django 5.0.6 on 2024-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_alter_payout_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
