# Generated by Django 5.0.6 on 2024-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0004_payout_partner_bankcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='did',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
