# Generated by Django 5.0.6 on 2024-08-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_bank_type'),
        ('payout', '0005_alter_payout_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='bankname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='orderno',
            field=models.CharField(default='', max_length=255),
        ),
    ]
