# Generated by Django 5.0.6 on 2024-08-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0007_alter_payout_bankname_alter_payout_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='bankname',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='did',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
