# Generated by Django 5.0.6 on 2024-08-02 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0008_alter_payout_bankname_alter_payout_did'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='bankcode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='partner_bankcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='payout',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payout_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
