# Generated by Django 5.0.6 on 2024-08-02 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0009_alter_payout_bankcode_alter_payout_partner_bankcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
