# Generated by Django 5.0.6 on 2024-08-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bank_bankcode'),
        ('payout', '0010_alter_payout_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payout.timeline')),
            ],
            options={
                'db_table': 'balance_timeline',
            },
        ),
    ]
