# Generated by Django 5.0.6 on 2024-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0012_alter_payout_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='money',
            field=models.BigIntegerField(),
        ),
    ]
