# Generated by Django 5.0.6 on 2024-12-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0014_alter_usertimeline_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='partner_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
