# Generated by Django 5.0.6 on 2024-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0015_payout_partner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='staging_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
