# Generated by Django 5.0.6 on 2025-01-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0016_payout_staging_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='memo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
