# Generated by Django 5.0.6 on 2025-05-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0018_payout_manual_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'license_keys',
            },
        ),
    ]
