# Generated by Django 5.0.6 on 2025-05-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0019_licensekeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekeys',
            name='mac',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
