# Generated by Django 5.0.6 on 2025-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0021_alter_licensekeys_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekeys',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
