# Generated by Django 5.0.6 on 2025-07-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0022_alter_licensekeys_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseKeys',
        ),
    ]
