# Generated by Django 5.0.6 on 2024-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cid',
            name='cardtype',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cid',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
