# Generated by Django 5.0.6 on 2025-07-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_cid_cardtype_cid_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerMapping',
        ),
    ]
